- git-integration-for-jira-self-managed/GitHub.md
Update headers
remove taxonomy 'labels'
updated image paths
> MK-300 Merge branch to main (GitHub sample preview page)

- git-integration-for-jira-self-managed/GitHub.md
> Mk 300 update docs main

- git-integration-for-jira-self-managed/AWS-CodeCommit-gij-self-managed.md
- git-integration-for-jira-self-managed/Azure-DevOps-Server-Team-Foundation-Services-(TFS)-gij-self-managed.md
- git-integration-for-jira-self-managed/Frequently-Asked-Questions-gij-self-managed.md
- git-integration-for-jira-self-managed/GitHub-Enterprise-Server-gij-self-managed.md
- git-integration-for-jira-self-managed/GitLab-com-CE-EE-gijsm-gij-self-managed.md
- git-integration-for-jira-self-managed/GitLab-gij-self-managed.md
- git-integration-for-jira-self-managed/Integration-Guides-gij-self-managed.md
- git-integration-for-jira-self-managed/Web-linking-gij-self-managed.md
> Update faq main index page links. Fix rest of integration guide pages

- git-integration-for-jira-self-managed/GIJ-plus-Scriptrunner-gij-self-managed.md
- git-integration-for-jira-self-managed/GitHub-gij-self-managed.md
Update code blocks, fix spacing etc
> Git 4707 scriptrunner feature docs

- git-integration-for-jira-self-managed/Avoid-OutOfMemory-exceptions-by-configuring-or-memory-allocation-with-Jira-to-accommodate-large-repositories-gij-self-managed.md
- git-integration-for-jira-self-managed/Cannot-auto-deploy-some-tracked-repositories-gij-self-managed.md
- git-integration-for-jira-self-managed/Connection-reset-when-accessing-the-database-gij-self-managed.md
- git-integration-for-jira-self-managed/Dangerous-use-of-multiple-connections-error-on-local-database-gij-self-managed.md
- git-integration-for-jira-self-managed/Duplicate-entry-0-for-key-PRIMARY-exceptions-in-log-gij-self-managed.md
- git-integration-for-jira-self-managed/Error-while-reindexing-Java-heap-space-Object-too-large,-rejecting-the-pack-gij-self-managed.md
- git-integration-for-jira-self-managed/Features-gij-self-managed.md
- git-integration-for-jira-self-managed/Frequently-Asked-Questions-gij-self-managed.md
- git-integration-for-jira-self-managed/Git-Integration-(Jira-Data-Center)-Video-Guides-gij-self-managed.md
- git-integration-for-jira-self-managed/Gitolite-integration--why-the-Git-integration-app-not-see-the-master-branch-gij-self-managed.md
- git-integration-for-jira-self-managed/Health-check--database-collation-gij-self-managed.md
- git-integration-for-jira-self-managed/Hooks-and-Webhooks-gij-self-managed.md
- git-integration-for-jira-self-managed/Indexing-error-Too-many-open-files-gij-self-managed.md
- git-integration-for-jira-self-managed/Installation-fails-when-installing-manually-gij-self-managed.md
- git-integration-for-jira-self-managed/Integration-Guides-gij-self-managed.md
- git-integration-for-jira-self-managed/Jira-index-error--IndexNotFoundException--no-segments-file-found.md
- git-integration-for-jira-self-managed/Malformed-input-or-input-contains-unmappable-characters-gij-self-managed.md
- git-integration-for-jira-self-managed/Personal-access-token-failing-azure-devops-integration-with-Not-Authorized-error-gij-self-managed.md
- git-integration-for-jira-self-managed/Problems-with-shared-home-on-azure-storage-gij-self-managed.md
- git-integration-for-jira-self-managed/Pull-request-index-error--JSONException-gij-self-managed.md
- git-integration-for-jira-self-managed/REST-API-gij-self-managed.md
- git-integration-for-jira-self-managed/Repositories-missing-from-azure-devops-integration-gij-self-managed.md
- git-integration-for-jira-self-managed/SQLException-'Incorrect-string-value'-in-merge-requests-gij-self-managed.md
- git-integration-for-jira-self-managed/SSH-key-file-format-is-invalid-gij-self-managed.md
- git-integration-for-jira-self-managed/Service-proxy-has-been-destroyed-exceptions-in-log-gij-self-managed.md
- git-integration-for-jira-self-managed/TFS-Not-authorized-exception-when-Jira-works-thru-proxy-gij-self-managed.md
- git-integration-for-jira-self-managed/Troubleshooting-articles-gij-self-managed.md
- git-integration-for-jira-self-managed/Unexpected-exception-parsing-XML-document-from-URL-error-in-log-gij-self-managed.md
- git-integration-for-jira-self-managed/Why-I-am-getting-the-error-git-upload-pack-not-permitted-gij-self-managed.md
- git-integration-for-jira-self-managed/Why-don't-I-see-the-Create-Branch-or-Pull-Request-features-gij-self-managed.md
Update footers and missing links
Fix typos and missing esc chars
Finalizing Data Center/self-managed docs
Confluence compare and display tests
Link and continuity tests
> MK-300 GIT-4997 Update page formats, fix links, fix missing imgs etc

- git-integration-for-jira-self-managed/Add-New-Integration-Type-API-(examples)-gij-self-managed.md
- git-integration-for-jira-self-managed/Add-New-Integration-gij-self-managed.md
- git-integration-for-jira-self-managed/Faq-Installation-and-setup-gij-self-managed.md
- git-integration-for-jira-self-managed/Faq-administration-gij-self-managed.md
- git-integration-for-jira-self-managed/Faq-developer-gij-self-managed.md
- git-integration-for-jira-self-managed/Faq-general-gij-self-managed.md
- git-integration-for-jira-self-managed/Faq-logging-gij-self-managed.md
- git-integration-for-jira-self-managed/Faq-purchase-and-pricing-gij-self-managed.md
- git-integration-for-jira-self-managed/Faq-reindex-and-cache-gij-self-managed.md
- git-integration-for-jira-self-managed/Faq-repositories-gij-self-managed.md
- git-integration-for-jira-self-managed/Faq-support-gij-self-managed.md
- git-integration-for-jira-self-managed/Faq-uninstall-and-reinstall-gij-self-managed.md
- git-integration-for-jira-self-managed/Faq-workspace-gij-self-managed.md
- git-integration-for-jira-self-managed/How-to-articles-gij-self-managed.md
- git-integration-for-jira-self-managed/Integration-API-gij-self-managed.md
- git-integration-for-jira-self-managed/Remove-Integration-gij-self-managed.md
- git-integration-for-jira-self-managed/Retrieve-Integration-List-gij-self-managed.md
- git-integration-for-jira-self-managed/Retrieve-an-Integration-gij-self-managed.md
- git-integration-for-jira-self-managed/Troubleshooting-articles-gij-self-managed.md
- git-integration-for-jira-self-managed/Update-Existing-Integration-gij-self-managed.md
- git-integration-for-jira-self-managed/faq-ssh-gij-self-managed.md
Add footers for continuity
Fix esc chars not showing on prod
> MK-300 GIT-4997 Fix layout and table formats, etc.

- git-integration-for-jira-self-managed/GitHub-GitHub-Enterprise-JMESPath-filter-examples-gij-self-managed.md
Added a spacer line between 2 examples
> Adding a new line between examples

- git-integration-for-jira-self-managed/How-to-create-a-HAR-file-and-send-it-to-support-for-analysis-gij-self-managed.md
- git-integration-for-jira-self-managed/Import-existing-repositories-via-Bulk-change-gij-self-managed.md
> GIT-5127 Update/fix imgs not displaying in GK HC

- git-integration-for-jira-self-managed/Deeplinking-feature-gij-self-managed.md
> GIT-5127 Edit and remove dup sentences

- git-integration-for-jira-self-managed/Reindex-POST-API-gij-self-managed.md
Backed up the one with the recent v4.17 info
> GIT-5127 Revert back pre-1.47 version of the Reindex POST REST API doc

- git-integration-for-jira-self-managed/Creating-Personal-Access-Tokens-gij-self-managed.md
- git-integration-for-jira-self-managed/Update-Existing-Integration-gij-self-managed.md
> GIT-5152 Update/fix spacing

- git-integration-for-jira-self-managed/Reindex-POST-API-gij-self-managed.md
After some few testing, removed array info and examples -- since they don't work and return errors.
> GIT-5152 / GIT-4695 Critical info update

- git-integration-for-jira-self-managed/Branches-(Development-panel)-gij-self-managed.md
- git-integration-for-jira-self-managed/Git-integration-features-gij-self-managed.md
> Git 5152 update docs main v4 17

- git-integration-for-jira-self-managed/App-Support-gij-self-managed.md
- git-integration-for-jira-self-managed/Documentation-gij-self-managed.md
> GIT-5230 Change doc version to 4.18

- git-integration-for-jira-self-managed/Tag-filters-gij-self-managed.md
Ready to merge.... has been reviewed
> GIT-5218 Update table info for tag filters

- git-integration-for-jira-self-managed/Tag-filters-gij-self-managed.md
> GIT-5218 Fix img url

- git-integration-for-jira-self-managed/error-creating-git-branches--GitLabPropertiesNotInitializedException-and-using-NFS-gij-self-managed.md
was gitcloud --< moved to git-data-center
> GIT-5218 change taxonomy to gitserver

- git-integration-for-jira-self-managed/Tag-filters-gij-self-managed.md
> GIT-5218 / GITCL-3418 minor fix

- git-integration-for-jira-self-managed/Adding-a-repository-hosted-on-Windows-Servers-or-Windows-Network-Share-(Admins)-gij-self-managed.md
- git-integration-for-jira-self-managed/Discard-cloned-files-in-Jira-Home-directory-(General-setting)-gij-self-managed.md
- git-integration-for-jira-self-managed/Documentation-gij-self-managed.md
- git-integration-for-jira-self-managed/Features-gij-self-managed.md
- git-integration-for-jira-self-managed/General-settings-Improving-Jira-performance-gij-self-managed.md
- git-integration-for-jira-self-managed/Getting-started-for-Git-administrators-gij-self-managed.md
- git-integration-for-jira-self-managed/Increasing-timeout-threshold-for-large-repositories-while-doing-a-Git-pull-gij-self-managed.md
- git-integration-for-jira-self-managed/Installation-and-updating-gij-self-managed.md
- git-integration-for-jira-self-managed/Installation-gij-self-managed.md
- git-integration-for-jira-self-managed/Installation-via-Atlassian-Marketplace-gij-self-managed.md
- git-integration-for-jira-self-managed/Installation-via-Jira-Plugin-Manager-gij-self-managed.md
- git-integration-for-jira-self-managed/Managing-license-key-gij-self-managed.md
- git-integration-for-jira-self-managed/Manual-installation-gij-self-managed.md
- git-integration-for-jira-self-managed/New-GitLab-v10-authentication-gij-self-managed.md
- git-integration-for-jira-self-managed/Recommended-reindex-interval-setting-gij-self-managed.md
- git-integration-for-jira-self-managed/Recommended-upgrade-method-for-Git-Integration-for-Jira-gij-self-managed.md
- git-integration-for-jira-self-managed/Reindex-API-to-trigger-indexing-gij-self-managed.md
- git-integration-for-jira-self-managed/Setting-up-repository-root-not-located-in-Jira-Home-directory-(Admins)-gij-self-managed.md
- git-integration-for-jira-self-managed/Setting-up-web-linking-gij-self-managed.md
- git-integration-for-jira-self-managed/Setting-up-webhooks-gij-self-managed.md
- git-integration-for-jira-self-managed/Setup-GitLab-Server-to-respond-to-incoming-network-API-calls-gij-self-managed.md
- git-integration-for-jira-self-managed/Working-with-SSH-keys-gij-self-managed.md
- git-integration-for-jira-self-managed/Working-with-Tracked-folders-gij-self-managed.md
Add new info links
Fix img alignment
Fix missing index links
> GIT-5218 Update/fix layout, spacing, readability etc.

- git-integration-for-jira-self-managed/App-Support-gij-self-managed.md
Update compatibility info to Jira 9.9
Add date EOL info
> GIT-5232 Add new compatibility info

- git-integration-for-jira-self-managed/scriptrunner-javadoc-git-rest-publicmodels-Tag-gij-self-managed.md
DO NOT MERGE YET
---
For review....
> GIT-5210 Remove unneeded methods from Tags scriptrunner

- git-integration-for-jira-self-managed/GitHub-App-integration-gij-self-managed.md
* * *
DO NOT MERGE YET
* * *
consolidating infos
> GIT-5281 Add missing info and requirements

- git-integration-for-jira-self-managed/Faq-logging-gij-self-managed.md
Remind to me -- update/add new troubleshooting article re: JMESPath GitHub
This commit adds a new section about debug level which is specifically for a GitHub issue
> GIT-5093 Write article "How to log GitHub responses"

- git-integration-for-jira-self-managed/App-Support-gij-self-managed.md
> GIT-5266 Update app support version and info

- git-integration-for-jira-self-managed/GitHub-Enterprise-Server-gij-self-managed.md
- git-integration-for-jira-self-managed/GitHub-gij-self-managed.md
> GIT-5333 Add new section from Gerrit integration guide

- git-integration-for-jira-self-managed/Working-with-Custom-API-Path-gij-self-managed.md
> Git 5333 update main docs v422

- git-integration-for-jira-self-managed/Microsoft-VSTS-TFS-Azure-Repos-JMESPath-filter-examples-gij-self-managed.md
- git-integration-for-jira-self-managed/Retrieve-an-Integration-gij-self-managed.md
Update JMESPath examples MS/Azure
> GIT-5383 / GITCL-3602

- git-integration-for-jira-self-managed/GitHub-App-JMESPath-filter-examples-gij-self-managed.md
DO NOT MERGE YET...
waiting for confirmation and review
> GIT-5492 Update/fix doc error - pipe operator for GH app JMESpath page

- git-integration-for-jira-self-managed/App-Support-gij-self-managed.md
- git-integration-for-jira-self-managed/Pull-or-merge-requests-(Development-panel)-gij-self-managed.md
Update server licence support info for Jira 9.13 (just in) 
Fix incorrect URL redirect page for PR link
> GIT-5594 Update app support info for Jira 9.13 upgrade

- git-integration-for-jira-self-managed/Manager-permissions-gij-self-managed.md
DO NOT MERGE YET...
Feature and API testing.....
> GIT-5433 Update info

- git-integration-for-jira-self-managed/gij5-serverdc-java8-depreciation-gij-self-managed.md
GIT-5823 Add new HC page for Java 8 deprecation w/ GIJ 5
> GIT-5823 Add new HC page for Java 8 deprecation w/ GIJ 5

- git-integration-for-jira-self-managed/Faq-reindex-and-cache-gij-self-managed.md
Pull request created in: https://jira.bigbrassband.com/browse/GIT-5221
> GIT-5221 Update reindex url and info

- git-integration-for-jira-self-managed/Add-New-Integration-Type-API-(examples)-gij-self-managed.md
- git-integration-for-jira-self-managed/Add-New-Integration-gij-self-managed.md
- git-integration-for-jira-self-managed/Add-New-Repository-gij-self-managed.md
- git-integration-for-jira-self-managed/Branches-API-gij-self-managed.md
- git-integration-for-jira-self-managed/Bulk-Export-gij-self-managed.md
- git-integration-for-jira-self-managed/Bulk-Import-gij-self-managed.md
- git-integration-for-jira-self-managed/Delete-Existing-Repository-gij-self-managed.md
- git-integration-for-jira-self-managed/Faq-reindex-and-cache-gij-self-managed.md
- git-integration-for-jira-self-managed/Get-Bulk-Import-Information-gij-self-managed.md
- git-integration-for-jira-self-managed/Get-Commit-Issue-Changes-gij-self-managed.md
- git-integration-for-jira-self-managed/Get-Commits-gij-self-managed.md
- git-integration-for-jira-self-managed/Reindex-API-to-trigger-indexing-gij-self-managed.md
- git-integration-for-jira-self-managed/Reindex-GET-API-gij-self-managed.md
- git-integration-for-jira-self-managed/Reindex-POST-API-gij-self-managed.md
- git-integration-for-jira-self-managed/Remove-Integration-gij-self-managed.md
- git-integration-for-jira-self-managed/Retrieve-Integration-List-gij-self-managed.md
- git-integration-for-jira-self-managed/Retrieve-Repository-List-gij-self-managed.md
- git-integration-for-jira-self-managed/Retrieve-an-Integration-gij-self-managed.md
- git-integration-for-jira-self-managed/Tags-API-gij-self-managed.md
- git-integration-for-jira-self-managed/Update-Commit-Issue-Changes-gij-self-managed.md
- git-integration-for-jira-self-managed/Update-Existing-Integration-gij-self-managed.md
- git-integration-for-jira-self-managed/Update-Existing-Repository-gij-self-managed.md
Pull request created in: https://jira.bigbrassband.com/browse/GIT-5221
> GIT-5221 Remove refs, update and fix urls etc

- git-integration-for-jira-self-managed/Jira-Data-Center-(High-availability-and-clustering)-gij-self-managed.md
- git-integration-for-jira-self-managed/Jira-Git-integration-development-panel-gij-self-managed.md
fix bulleted list item display issue
html hack
> Git 6001 release 428 docs

- git-integration-for-jira-self-managed/Exporting-repository-configuration-via-Bulk-change-gij-self-managed.md
Fix screenshot for Bulk Change Export Configuration dialog
> Fix screenshot for export dialog HC-137

- git-integration-for-jira-self-managed/JQL-searching-gij-self-managed.md
Pull request created in: https://gitkraken.atlassian.net/browse/GIT-5134 by the Git Integration for Jira app.
> Merge GIT-5134- to main

- git-integration-for-jira-self-managed/App-Support-gij-self-managed.md
Add info for Jira version, EOL and IE Edge support
> GIT-6001 / GIT-6126 / GIT-5604 App support

- git-integration-for-jira-self-managed/Avoid-OutOfMemory-exceptions-by-configuring-or-memory-allocation-with-Jira-to-accommodate-large-repositories-gij-self-managed.md
- git-integration-for-jira-self-managed/Cannot-auto-deploy-some-tracked-repositories-gij-self-managed.md
- git-integration-for-jira-self-managed/Connection-reset-when-accessing-the-database-gij-self-managed.md
- git-integration-for-jira-self-managed/Dangerous-use-of-multiple-connections-error-on-local-database-gij-self-managed.md
- git-integration-for-jira-self-managed/Duplicate-entry-0-for-key-PRIMARY-exceptions-in-log-gij-self-managed.md
- git-integration-for-jira-self-managed/Error-while-reindexing-Java-heap-space-Object-too-large,-rejecting-the-pack-gij-self-managed.md
- git-integration-for-jira-self-managed/FIxing-reindex-issues-using-Indexing-queue-viewer-gij-self-managed.md
- git-integration-for-jira-self-managed/Fix-performance-issues-for-nested-cloned-repositories-with-enabled-secure-mode-gij-self-managed.md
- git-integration-for-jira-self-managed/GitLab-gij-self-managed.md
- git-integration-for-jira-self-managed/Gitolite-integration--why-the-Git-integration-app-not-see-the-master-branch-gij-self-managed.md
- git-integration-for-jira-self-managed/Indexing-error-Too-many-open-files-gij-self-managed.md
- git-integration-for-jira-self-managed/Installation-fails-when-installing-manually-gij-self-managed.md
- git-integration-for-jira-self-managed/Jira-index-error--IndexNotFoundException--no-segments-file-found.md
- git-integration-for-jira-self-managed/Malformed-input-or-input-contains-unmappable-characters-gij-self-managed.md
- git-integration-for-jira-self-managed/Personal-access-token-failing-azure-devops-integration-with-Not-Authorized-error-gij-self-managed.md
- git-integration-for-jira-self-managed/Problems-with-shared-home-on-azure-storage-gij-self-managed.md
- git-integration-for-jira-self-managed/Repositories-missing-from-azure-devops-integration-gij-self-managed.md
- git-integration-for-jira-self-managed/SQLException-'Incorrect-string-value'-in-merge-requests-gij-self-managed.md
- git-integration-for-jira-self-managed/SSH-key-file-format-is-invalid-gij-self-managed.md
- git-integration-for-jira-self-managed/Service-proxy-has-been-destroyed-exceptions-in-log-gij-self-managed.md
- git-integration-for-jira-self-managed/TFS-Not-authorized-exception-when-Jira-works-thru-proxy-gij-self-managed.md
- git-integration-for-jira-self-managed/Troubleshooting-articles-gij-self-managed.md
- git-integration-for-jira-self-managed/Unexpected-exception-parsing-XML-document-from-URL-error-in-log-gij-self-managed.md
- git-integration-for-jira-self-managed/Why-I-am-getting-the-error-git-upload-pack-not-permitted-gij-self-managed.md
- git-integration-for-jira-self-managed/Your-token-has-not-been-granted-the-required-scopes-gij-self-managed.md
- git-integration-for-jira-self-managed/creating-and-configuring-ssh-keys-windows-macos-linux-gij-self-managed.md
- git-integration-for-jira-self-managed/edDSA-provider-not-supported-WARN-in-logs.md
- git-integration-for-jira-self-managed/error-creating-git-branches--GitLabPropertiesNotInitializedException-and-using-NFS-gij-self-managed.md
- git-integration-for-jira-self-managed/when-a-license-expires-a-session-error-is-shown-to-the-user-gij-self-managed.md
edDSA workaround
GAT Gitlab support feature
infobit in ssh key doc
Add/update new info
---
formatting and editing............
> GIT-6001 / GIT-4647 / GIT-4618 / GIT-4942

- git-integration-for-jira-self-managed/Cancel-indexing-revision-indexing-gij-self-managed.md
- git-integration-for-jira-self-managed/Indexing-queue-viewer-gij-self-managed.md
small info re: cancel delete queue
> Git 6001 release 500 plus and jira10 docs

- git-integration-for-jira-self-managed/App-Support-gij-self-managed.md
- git-integration-for-jira-self-managed/Azure-DevOps-Server-Team-Foundation-Services-(TFS)-gij-self-managed.md
- git-integration-for-jira-self-managed/Azure-DevOps-Visual-Studio-Team-Services-(VSTS)-gij-self-managed.md
- git-integration-for-jira-self-managed/GitHub-Enterprise-Server-gij-self-managed.md
- git-integration-for-jira-self-managed/GitHub-gij-self-managed.md
- git-integration-for-jira-self-managed/GitLab-com-CE-EE-gijsm-gij-self-managed.md
> GIT-6062 GIT-5245 Add support info
